AutomotiveHub/Controllers/CarController.cs
using AutomotiveHub.Core.Contracts;
using AutomotiveHub.Core.Extension;
using AutomotiveHub.Core.Models.Cars;
using AutomotiveHub.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static AutomotiveHub.Areas.Constants.UserConstants;
using static AutomotiveHub.Core.Constants.MessageConstants;

namespace AutomotiveHub.Controllers
{
    public class CarController : BaseController
    {
        private readonly ICarService carService;
        private readonly IDealerService dealerService;

        private readonly ILogger logger;

        public CarController(ICarService _carService, IDealerService _dealerService, ILogger<CarController> _logger)
        {
            carService = _carService;
            dealerService = _dealerService;
            logger = _logger;
        }

        //1
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] CarsQueryModel model)
        {

            var query = await carService.AllAsync(
                model.Category,
                model.SearchQuery,
                model.Sorting,
                model.CurrentPage,
                CarsQueryModel.CarsPerPage);


            model.TotalCarsCount = query.TotalCarsCount;
            model.Cars = query.Cars;

            model.Categories = await carService.AllCategoriesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            var userId = User.Id();

            IEnumerable<CarServiceModel> model;

            if (await dealerService.ExistsByIdAsync(userId) || User.IsInRole(AdminRole))
            {
                var dealerId = await dealerService.GetDealerId(userId);

                model = await carService.AllCarsByDealerId(dealerId);
            }
            else
            {
                model = await carService.AllCarsByUserId(userId);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string info)
        {
            if (!await carService.ExistsAsync(id))
            {
                return BadRequest();
            }

            var model = await carService.GetCarsDetailsIdAsync(id);
            var modelInfo = model.GetInformation();

            if (modelInfo != model.GetInformation())
            {
                return BadRequest();
            }

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new CarFormModel()
            {
                Categories = await carService.AllCategoriesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CarFormModel carModel)
        {
            if (!ModelState.IsValid)
            {
                carModel.Categories = await carService.AllCategoriesAsync();
            }

            if (await carService.CategoryExistAsync(carModel.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(carModel.CategoryId), CategoryNotExists);
            }

            int dealerId = await dealerService.GetDealerId(User.Id());
            int newCarId;

            try
            {
                newCarId = await carService.CreateCarAsync(carModel, dealerId);
            }
            catch (Exception)
            {

                TempData[Error] = CouldNotCreateCar;
                return View(carModel);
            }

            TempData["message"] = "You have successfully added new car";

            return RedirectToAction(nameof(Details), new { id = newCarId, information = carModel.GetInformation() });
        }

        [HttpPost]
        public async Task<IActionResult> Rent(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await dealerService.ExistsByIdAsync(User.Id()) && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (await carService.IsRentedAsync(id))
            {
                return BadRequest();
            }

            try
            {
                await carService.Rent(id, User.Id());
            }
            catch (Exception)
            {

                TempData[Error] = CannotRent;
                return RedirectToAction(nameof(All));
            }
            TempData[Success] = SuccessfulRent;

            return RedirectToAction(nameof(Mine));
        }

        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (!await carService.IsRentedByUserId(id, User.Id()))
            {
                return Unauthorized();
            }

            try
            {
                await carService.LeaveAsync(id);
            }
            catch (UnauthorizedAccessException ex)
            {

                logger.LogError(ex, "CarController/Leave");

                return Unauthorized();
            }

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasDealerWithIdAsync(id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var car = await carService.GetCarsDetailsIdAsync(id);

            int categoryId = await carService.GetCarCategoryId(car.Id);

            var model = new CarFormModel()
            {
                Brand = car.Brand,
                Year = car.Year,
                Model = car.Model,
                Kilometers = car.Kilometers,
                Description = car.Description,
                PricePerDay = car.PricePerDay,
                Fuel = car.Fuel,
                Transmission = car.Transmission,
                ImageUrl = car.ImageUrl,
                CategoryId = categoryId,
                Categories = await carService.AllCategoriesAsync()

            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CarFormModel carModel)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasDealerWithIdAsync(id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (await carService.CategoryExistAsync(carModel.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(carModel.CategoryId), "Category does not exist!");
            }

            if (ModelState.IsValid)
            {
                carModel.Categories = await carService.AllCategoriesAsync();

                return View(carModel);
            }

            await carService.EditAsync(id, carModel);

            return RedirectToAction(nameof(Details), new { id, info = carModel.GetInformation() });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasDealerWithIdAsync(id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var car = await carService.GetCarsDetailsIdAsync(id);

            var model = new CarDetailsViewModel()
            {
                Id = id,
                Brand = car.Brand,
                Model = car.Model,
                ImageUrl = car.ImageUrl,
                Category = car.Category
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CarDetailsViewModel carModel)
        {
            if (await carService.ExistsAsync(carModel.Id) == false)
            {
                return BadRequest();
            }
            if (await carService.HasDealerWithIdAsync(carModel.Id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            await carService.DeleteAsync(carModel.Id);

            return RedirectToAction(nameof(All));
        }
    }
}

AutomotiveHub/Controllers/DealerController.cs
using AutomotiveHub.Core.Contracts;
using AutomotiveHub.Core.Models.Dealer;
using AutomotiveHub.Extensions;
using Microsoft.AspNetCore.Mvc;
using static AutomotiveHub.Core.Constants.MessageConstants;
using static AutomotiveHub.Areas.Constants.UserConstants;
using AutomotiveHub.Attributes;
using AutomotiveHub.Core.Constants;

namespace AutomotiveHub.Controllers
{
    public class DealerController : BaseController
    {
        private readonly IDealerService dealerService;

        public DealerController(IDealerService _dealerService)
        {
            dealerService = _dealerService;
        }

        [HttpGet]
        [NotADealer]
        public async Task<IActionResult> Become()
        {
            if (await dealerService.ExistsByIdAsync(User.Id()))
            {
                return RedirectToAction(nameof(HomeController.Index), "Home", new {DealerMessage });

            }

            return View();
        }

        [HttpPost]
        [NotADealer]
        public async Task<IActionResult> Become(BecomeDealerServiceModel model)
        {
            var userId = User.Id();

            if (await dealerService.HasDealerPhoneNumber(model.PhoneNumber))
            {
                ModelState.AddModelError(nameof(model.PhoneNumber), DealerPhoneExists);
            }

            if (await dealerService.ExistsByIdAsync(User.Id()))
            {
                return RedirectToAction(nameof(HomeController.Index), "Home", new { DealerMessage });
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await dealerService.CreateAsync(User.Id(), model.PhoneNumber, model.Name);

            return RedirectToAction(nameof(CarController.All), "Car");
        }

        [HttpGet]
        [MustBeADealer]
        public async Task<IActionResult> AddDealership()
        {
            if (await dealerService.ExistsByIdAsync(User.Id()) == false)
            {
                return BadRequest();
            }

            return View(new AddDealershipServiceModel()
            {
                Cities = await dealerService.AllCitiesAsync()
            });
        }

        [HttpPost]
        [MustBeADealer]
        public async Task<IActionResult> AddDealership(AddDealershipServiceModel model)
        {
            var userId = User.Id();

            if (await dealerService.ExistsByIdAsync(userId) == false)
            {
                return BadRequest();
            }

            if (await dealerService.CityExistsById(model.CityId)==false)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                model.Cities = await dealerService.AllCitiesAsync();

                return View(model);
            }

            try
            {
                await dealerService.AddDealershipAsync(userId, model);
            }
            catch (Exception)
            {
                TempData[MessageConstants.Error] = "Something get wrong! Check your data!";

                return View(model);
            }

            return RedirectToAction(nameof(CarController.All), "Car");
        }
    }
}

AutomotiveHub/Views/Shared/DefaultDealer.cshtml
@inject IDealerService dealerService

<ul class="navbar-nav flex-grow-2">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="All">All Houses</a>
    </li>
    @if (this.User?.Identity?.IsAuthenticated ?? false)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Mine">My Houses</a>
        </li>
        @if (await dealerService.ExistsByIdAsync(User.Id()))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Add">Add House</a>
            </li>
        }
    }
</ul>

AutomotiveHub/Views/Shared/_CarFormPartial.cshtml
@model CarFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Brand"></label>
                <input asp-for="Brand" class="form-control" placeholder="Audi...">
                <span asp-validation-for="Brand" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="RS6...">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year"></label>
                <input asp-for="Year" class="form-control" placeholder="2...">
                <span asp-validation-for="Year" class="small text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="Write a description about the vehicle..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your URL goes here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePerDay"></label>
                <input asp-for="PricePerDay" class="form-control" placeholder="199...">
                <span asp-validation-for="PricePerDay" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fuel"></label>
                <select asp-for="Fuel" class="form-control">
                    <option value="0">Diesel</option>
                    <option value="1">Petrol</option>
                    <option value="2">LPG</option>
                    <option value="3">Electrical</option>
                </select>
                <span asp-validation-for="Fuel" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transmission"></label>
                <select asp-for="Transmission" class="form-control">
                    <option value="0">Automatic</option>
                    <option value="1">Manual</option>
                </select>
                <span asp-validation-for="Transmission" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

AutomotiveHub/Views/Shared/_CarPartial.cshtml
@model CarServiceModel
@inject ICarService carService
@inject IDealerService dealerService

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Car Image">
        <div class="card-body text-center">
            <h4>@Model.Brand</h4>
            <h6>Model: <b>@Model.Model</b></h6>
            <h6>Fuel: <b>@Model.Fuel</b></h6>
            <h6>Transmission: <b>@Model.Transmission</b></h6>
            <h6>
                Price Per Day:
                <b>@String.Format("{0:f2}", Model.PricePerDay) BGN</b>
            </h6>
            <h6>(@(Model.IsRented ? "Rented" : "Not Rented"))</h6>
            <br />
            <a asp-controller="Car" asp-action="Details" asp-route-id="@Model.Id"
               asp-route-information="@Model.GetInformation()" class="btn btn-success">Details</a>

            @if (this.User.Identity.IsAuthenticated)
            {
                if (await carService.HasDealerWithIdAsync(Model.Id, User.Id()) || User.IsAdmin())
                {
                    <a asp-area="" asp-controller="Car" asp-action="Edit" asp-route-id="@Model.Id"
                       class="btn btn-warning">Edit</a>
                    <a asp-area="" asp-controller="Car" asp-action="Delete" asp-route-id="@Model.Id"
                       class="btn btn-danger">Delete</a>
                }

                <p></p>
                @if (!Model.IsRented && ((await dealerService.ExistsByIdAsync(User.Id())) == false || User.IsAdmin()))
                {
                    <form class="input-group-sm" asp-controller="Car"
                          asp-area="" asp-action="Rent" asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-primary" type="submit" value="Rent" />
                    </form>
                }
                else if (await carService.IsRentedByUserId(Model.Id, User.Id()))
                {
                    <form asp-area="" asp-controller="Car" asp-action="Leave"
                          asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-primary" type="submit" value="Leave" />
                    </form>
                }
            }
        </div>
    </div>
</div>

AutomotiveHub/Views/Shared/_Layout.cshtml
@inject IDealerService dealerService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutomotiveHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutomotiveHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>   
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://i.pinimg.com/564x/2c/5f/c8/2c5fc8674717fef1ea07107edc348a42.jpg" alt="AutomotiveHub Logo" height="70" width="auto">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="All">All Cars</a>
                        </li>
                        @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Mine">My Cars</a>
                            </li>
                        }
                        
                        
                        @if (await dealerService.ExistsByIdAsync(User.Id()) || User.IsInRole(AdminRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Add">Add Car</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dealer" asp-action="AddDealership">Add Dealership</a>
                            </li>
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark text-white text-center py-0">
        <div class="container">
            &copy; @DateTime.Today.Year - AutomotiveHub -
            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
            <span class="mx-2">|</span>
            <a asp-area="" asp-controller="Home" asp-action="AboutUs" class="text-white">About Us</a>
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>